#!/bin/sh

echo "Running pre-commit checks..."

# Check if only Python files are changed
PYTHON_ONLY=true
for file in $(git diff --cached --name-only); do
    if [[ ! $file == python/* ]]; then
        PYTHON_ONLY=false
        break
    fi
done

if [ "$PYTHON_ONLY" = true ]; then
    echo "Only Python files changed, skipping TypeScript checks."
else
    echo "Running linter and fixing issues..."
    # Run linter and fix issues
    cd typescript && pnpm lint:fix 

    echo "Building the project..."
    # Build the project
    pnpm build

    # Exit with an error if any of the above commands fail
    if [ $? -ne 0 ]; then
        echo "Pre-commit checks failed."
        exit 1
    fi
fi

echo "Pre-commit checks completed."
